#! /bin/bash

# Shell Scripting Tutorial for Beginners 7 - How to append output to the end of text file

# https://www.youtube.com/watch?v=0Z72-LpvwjU&list=PLS1QulWo1RIYmaxcEqw5JhK3b-6rgdWO_&index=7

# APPEND TEXT TO A FILE

echo -e "Enter the name of the File : \c" 

read file_name

if [ -f $file_name ] 

then
 	if [ -w $file_name ]
 	then
 		#  ctrl + d : to leave "cat" command
 		# > : overwritten;  >> : append text to a file
 		echo "Type some text data. To quit press ctrl + d. "
 		cat >> $file_name

 	else
 		echo "The file does not have WRITE PERMISSION."
 	fi

else 
 echo "$file_name not exists"
fi