#! /bin/bash

# tut24: Local Var


function print(){

	local name=$1       # local var
	echo "the name is $name"

}

name="Tom"   # globral var

echo "My name is $name"


print Max  # needs "local", otherwise, it will be Max after asign its value to the function

echo "His name is $name : After"




