#! /bin/bash -x

# tut28: DEBUG


# debug option:  bash -x [bash file]
# 或者在第一行 .../bash -x
# for debugging section:  
	# set -x 
	# [section for debug]   
	# set +x



file=/Users/cheng-changchou/Documents/MyGit/bashTut/file.txt

trap "rm -f $file && echo file deleted; exit" 0 2 15 

echo "pid is $$"   # $$: pid of the script

# loop
while (( COUNT < 10 ))
do
	sleep 10
	(( COUNT ++ ))
	echo $COUNT
done
exit 0   # Ctrl + Z: Suspend signal



