#! /bin/bash

# tut20: FOR LOOP for COMMANDS


for command in ls pwd date
	do 
		echo "----------$command------------"
		$command
	done



echo "----------PRINT OUT Directory------------"
for item in *
	do 
		if [ -d $item ]
		then
			echo $item
		fi
	done



echo "----------PRINT OUT ALL FILES------------"
for item in *
	do 
		if [ -f $item ]
		then
			echo $item
		fi
	done

